### ISSUE TITLE
First letter of files in ISO are cut of

### ISSUE THREAD

**Issue by dartmann** [iquirino/IsoCreatorTool#1]
Hi, although this seems not maintained I want to provide some feedback: after installing your binary (Windows 10 x64, 1809) and creating an ISO of a CDROM, the ISO file contains all files with a cut of first letter (e.g. README.txt -> EADME.txt). Maybe you are motivated to fix this? 😉 Kind regards, David

**Comment by iquirino** [comment]
I will test it, thank you by your time.

**Comment by iquirino** [comment]
I tried and i'm not able to simulate your issue.
My iso was created correctly.

Can you provide a Zip file simulate your issue?

Thank you!

**Comment by iquirino** [comment]
No response.

**Comment by dartmann** [comment]
@iquirino sorry for not answering your request. I was totally overloaded with work. This issue is no big deal and not even reproducable by yourself. So just keep it closed. That's fine. Thank you anyway for trying to help me out. I appreciate that.
