### ISSUE TITLE
First letter cut off files and folders

### ISSUE THREAD

**Issue by bastler2** [iquirino/IsoCreatorTool#2]
Hi, i have reproduced the Issue #1 which not got resolved :)

When ( in the ShellViewModel.cs - line 122 & line 139 ) it starts to add files to the builder ( CDBuilder ) it makes substrings and cuts off the first letter of the filename/foldername.

file = "H:/data1.cab";
this.Folder = "H:/"

file.Substring(this.Folder.Length + 1);

and out comes "H:/ata1.cab"
the same is for the folders in line 122

when i remove the +1 in line 122 & 139 it works just fine for me

Hope this helps :)

**Comment by vinhtvu2** [comment]
Just ran into this same issue.

**Comment by iquirino** [comment]
@bastler2 I'm sorry for late.
@vinhtvu2 or @bastler2, Can you create a Pull Request with the solution?
Thank you!

**Comment by vinhtvu2** [comment]
PR in.
https://github.com/iquirino/IsoCreatorTool/pull/3

**Comment by iquirino** [comment]
> PR in. #3

THANK YOU!!!
